#USER

### get all users
GET http://127.0.0.1:8000/users/ HTTP/1.1
Content-Type: application/json

### create a user
POST http://127.0.0.1:8000/users/ HTTP/1.1
Content-Type: application/json

{
    "name": "Daniel",
    "email": "testando123@gmail.com",
    "password": "302010"

}

### get user by id
GET http://127.0.0.1:8000/users/633cb6a8d5f20373e15ca2c6 HTTP/1.1
Content-Type: application/json

### get user by email
GET http://127.0.0.1:8000/users/email/testando1@gmail.com HTTP/1.1
Content-Type: application/json

### delete user by email
DELETE HTTP://127.0.0.1:8000/users/t@gmail.com

