#USER

### get all users
GET http://127.0.0.1:8000/users/ HTTP/1.1
Content-Type: application/json

### create a user
POST http://127.0.0.1:8000/users/ HTTP/1.1
Content-Type: application/json

{
    "name": "Daniel Oliveira",
    "email": "testando1@gmail.com",
    "password": "302010"

}

### get user by id
GET http://127.0.0.1:8000/users/632b768a78d2d3fcd54dee2a HTTP/1.1
Content-Type: application/json

### get user by email
GET http://127.0.0.1:8000/users/email/testando1@gmail.com HTTP/1.1
Content-Type: application/json

### delete user by email
DELETE HTTP://127.0.0.1:8000/users/testando1@gmail.com

