

### get open cart by user id 
# Consultar os carrinhos fechados de um cliente
GET http://127.0.0.1:8000/order/testando2@gmail.com
Content-Type: application/json

# Consultar quantos carrinhos fechados um cliente possui
GET http://127.0.0.1:8000/order/count/testando@gmail.com
Content-Type: application/json

# Consultar os produtos e suas quantidades em carrinhos fechados
GET http://127.0.0.1:8000/order/product_code/1234
Content-Type: application/json

# Excluir pedido do cliente
DELETE  http://127.0.0.1:8000/order/cart_id
Content-Type: application/json