### creating a address passing user id as parameter 
POST http://127.0.0.1:8000/address/testando1@gmail.com HTTP/1.1
Content-Type: application/json

[
{
    "street": "i know ",
    "number": 10,
    "zipcode": "9999-030",
    "district": "Grass Lands",
    "city": "stark tower",
    "state": "Parallel Universe", 
    "is_delivery": true
                        
},
{

    "street": "iddk",
    "number": 21,
    "zipcode": "9899-080",
    "district": "Grass Lands",
    "city": "stark tower",
    "state": "Parallel Universe", 
    "is_delivery": false
                        
}
]

### getting address passing user email as parameter 
GET http://127.0.0.1:8000/address/testando3@gmail.com HTTP/1.1
Content-Type: application/json

### getting address passing user email as parameter 
DELETE http://127.0.0.1:8000/address/testando3@gmail.com HTTP/1.1
Content-Type: application/json
