# PRODUCT

### create a product
POST http://127.0.0.1:8000/products/ HTTP/1.1
Content-Type: application/json

{ 
  "name": "Ração Premiere",
  "description": "Raças Específicas Lhasa Apso Cães Adultos",
  "price": 124.9,
  "image": "https://static.petz.com.br/fotos/1656091760542.jpg",
  "code": 12345,
  "type_animal": "dog",
  "category": "food",
  "qt_stock": 6
}

### get product by name of the product
#Obs: para colocar espaço no nome do produto, substituir espaço por %20
GET http://127.0.0.1:8000/products/name/Ração Premier HTTP/1.1
Content-Type: application/json

### get product by code of the product
GET http://127.0.0.1:8000/products/code/1243 HTTP/1.1
Content-Type: application/json

### update product by code of the product
PUT http://127.0.0.1:8000/products/1243 HTTP/1.1
Content-Type: application/json

{ 
  "name": "Ração Premier 2",
  "description": "Raças Específicas Lhasa Apso Cães Adultos",
  "price": 124.9,
  "image": "https://static.petz.com.br/fotos/1656091760542.jpg",
  "type_animal": "dog",
  "category": "food",
  "qt_stock": 15
}

### delete product by code of the product
DELETE HTTP://127.0.0.1:8000/products/1243 HTTP/1.1
Content-Type: application/json