

## creating a cart associated with the user, passing id_usuario
POST http://127.0.0.1:8000/cart/6340a88195cd936cf9740a4b/1234 HTTP/1.1
Content-Type: application/json


### get open cart by user id 
GET http://127.0.0.1:8000/cart/633f54b94628a8758095fd68
Content-Type: application/json


### delete the cart passing as a parameter a cart id
DELETE HTTP://127.0.0.1:8000/cart/633f54d94628a8758095fd69
Content-Type: application/json


### delete cart product by user and product code
DELETE HTTP://127.0.0.1:8000/cart/6340a88195cd936cf9740a4b/1234
Content-Type: application/json



