version: "3"

services:
  api:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - database
    environment:
      - DATABASE_URI=mongodb+srv://anavitoriasln:309045@luizacode.6qc7miw.mongodb.net/test
  database:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db