version: "3"

services:
  api:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - database
    environment:
      - DATABASE_URI=mongodb+srv://Grupo9:x6ms8x067CJh4br7@projetofinal-luizacode.wj3w8ev.mongodb.net/test
  database:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db